""" List of redis keys for the robot
"""
ROBOT_KEY = "robot::"

ROBOT_RESET_COMPL_KEY = ROBOT_KEY + "reset_complete"
ROBOT_CMD_TYPE_KEY = ROBOT_KEY + "cmd_type"
ROBOT_ENV_CONN_KEY = ROBOT_KEY + "env_connected"
ROBOT_CMD_TSTAMP_KEY = ROBOT_KEY + "cmd_tstamp"
ROBOT_LAST_CMD_TSTAMP = ROBOT_KEY + "last_cmd_tstamp"
ROBOT_SET_GRIPPER_CMD = ROBOT_KEY + "set_gripper_value"

STATE_KEY = "proprio::"
ROBOT_STATE_KEY =  ROBOT_KEY + STATE_KEY
ROBOT_STATE_TSTAMP_KEY = ROBOT_STATE_KEY + "tstamp"
ROBOT_STATE_Q_KEY = ROBOT_STATE_KEY + "q"
ROBOT_STATE_DQ_KEY = ROBOT_STATE_KEY + "dq"
ROBOT_STATE_EE_POS_KEY = ROBOT_STATE_KEY + "ee_position"
ROBOT_STATE_EE_ORN_KEY = ROBOT_STATE_KEY + "ee_orientation"
ROBOT_STATE_EE_POSE_KEY = ROBOT_STATE_KEY + "ee_pose"
ROBOT_STATE_EE_V_KEY = ROBOT_STATE_KEY +"ee_v"
ROBOT_STATE_EE_OMEGA_KEY = ROBOT_STATE_KEY + "ee_omega"
ROBOT_STATE_TAU_KEY = ROBOT_STATE_KEY + "tau"


MODEL_KEY = "model::"
ROBOT_MODEL_KEY = ROBOT_KEY + MODEL_KEY
ROBOT_MODEL_JACOBIAN_KEY = ROBOT_MODEL_KEY + "jacobian"
ROBOT_MODEL_L_JACOBIAN_KEY = ROBOT_MODEL_KEY + "linear_jacobian"
ROBOT_MODEL_A_JACOBIAN_KEY = ROBOT_MODEL_KEY + "angular_jacobian"
ROBOT_MODEL_MASS_MATRIX_KEY = ROBOT_MODEL_KEY + "mass_matrix"


CONTROL_KEY = "controller::"
CONTROLLER_CONTROL_TYPE_KEY = CONTROL_KEY + "control_type"
CONTROLLER_GOAL_KEY = CONTROL_KEY + "goal"
CONTROLLER_CONTROL_PARAMS_KEY = CONTROL_KEY + "control_params"